### ISSUE TITLE
Flash Problem

### ISSUE THREAD

**Issue by Prashanth9reddy** [SanketHiremath/DA14531-HMC5883L-BLE-Interface#1]
Hi after flashing your code I am unable flash another code (for examole blinky example). Have you changed any configurations on code.

**Comment by SanketHiremath** [comment]
Hi, I will have a look at it.

**Comment by SanketHiremath** [comment]
Looks like it's a bug in the SDK, I haven't  changed any default configurations with respect to the SPI . But the hotfix for this problem is to upload the code  "spi_flash"  available at "SmartSnippetsStudio2.0.14\DA145xx_SDK\6.0.14.1114\projects\target_apps\peripheral_examples\spi\spi_flash " and then try reprogramming the flash using DialogSemi flash programmer software. Let me know if it works for you.
